FROM ubuntu:20.04

#RUN update-locale LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN apt clean && apt update && apt upgrade -y && apt install -y locales
RUN locale-gen en_US.UTF-8
CMD /bin/bash
