FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt clean && apt update && apt upgrade -y && apt install -y locales systemd
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8
RUN timedatectl set-timezone Europe/Berlin
CMD /bin/bash
